################################################################################
# HELM CHART DEFINITION FILE FOR TASKSTREAM AI AUTHENTICATION SERVICE
# ------------------------------------------------------------------------------
# FILE DESCRIPTION:
#   This Chart.yaml file provides comprehensive metadata and dependency 
#   declarations for deploying the TaskStream AI authentication service, 
#   ensuring an enterprise-grade, secure, and multi-region capable Helm chart.
#
# RELEVANT TECHNICAL SPECIFICATIONS:
#   1) Authentication Service Deployment (Tech Spec 8.1)
#      - Defines chart metadata for multi-region AWS EKS clusters, 
#        high availability, and SOC 2 Type II-level security.
#   2) Container Orchestration (Tech Spec 8.4)
#      - Outlines chart dependencies responsible for ingress and monitoring
#        integrations essential to orchestrating the auth service.
#   3) Security Standards (Tech Spec 7.1, 7.3)
#      - Incorporates robust scanning annotations and references 
#        to external dependencies for verifying compliance.
#
# INTERNAL IMPORTS (IE1):
#   - "auth-values" from "infrastructure/helm/values/auth.yaml" is 
#     the default values file used by this chart for authentication 
#     service configuration, including security contexts and 
#     autoscaling settings. Adjust or override via Helm CLI or CI/CD 
#     pipelines as needed.
#
# EXTERNAL IMPORTS (IE2): 
#   - AWS Load Balancer Controller (aws-load-balancer-controller v1.4.6) 
#     for secure ingress in AWS EKS (ingress.enabled).
#   - Prometheus Operator (prometheus-operator v45.0.0) for monitoring 
#     and security auditing integration (monitoring.enabled).
#
# EXPORTS (IE3):
#   - Exports the helm-chart metadata named "Chart" with the following:
#       - name (string)
#       - version (string)
#       - dependencies (array)
#     Used for consistent reference and secure deployment in multi-region
#     Kubernetes clusters.
################################################################################

apiVersion: v2
name: taskstream-auth
description: >-
  Enterprise-grade authentication service for TaskStream AI platform with
  SOC 2 Type II compliance, multi-region support, and integrated security controls.
type: application

################################################################################
# Versioning
# ------------------------------------------------------------------------------
# version: The chart's version. Should align with semver best practices for
#          tracking changes and backward compatibility.
# appVersion: The version of the application that this chart deploys. Maintained
#             separately to allow updates to the application code without
#             necessarily updating chart metadata.
################################################################################
version: "1.0.0"
appVersion: "1.0.0"

################################################################################
# Keywords
# ------------------------------------------------------------------------------
# A list of keywords for search and discoverability in artifact repositories.
################################################################################
keywords:
  - "authentication"
  - "oauth2"
  - "oidc"
  - "taskstream"
  - "microservice"
  - "security"
  - "multi-region"
  - "enterprise"

################################################################################
# Maintainers
# ------------------------------------------------------------------------------
# Provides contact information for the team or individuals maintaining this chart.
################################################################################
maintainers:
  - name: "TaskStream DevOps Team"
    email: "devops@taskstream.ai"
    url: "https://taskstream.ai/support"

################################################################################
# Chart Annotations
# ------------------------------------------------------------------------------
# Additional metadata consumed by various tooling (e.g., Artifact Hub).
################################################################################
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: "Apache-2.0"
  security.taskstream.io/scanned: "true"

################################################################################
# Dependencies
# ------------------------------------------------------------------------------
# Declares needed sub-charts or packages for the auth service:
#   1) aws-load-balancer-controller (v1.4.6) # external library version
#      - Manages AWS load balancers for secure ingress routing.
#   2) prometheus-operator (v45.0.0) # external library version
#      - Provides advanced monitoring and alerting capabilities.
################################################################################
dependencies:
  - name: aws-load-balancer-controller
    version: "1.4.6"  # external library version
    repository: "https://aws.github.io/eks-charts"
    condition: "ingress.enabled"
    tags:
      - "ingress"
      - "aws"

  - name: prometheus-operator
    version: "45.0.0"  # external library version
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: "monitoring.enabled"
    tags:
      - "monitoring"
      - "security"

################################################################################
# Engine Compatibility
# ------------------------------------------------------------------------------
# Specifies the minimum required Helm version for this chart, ensuring
# all features used here (e.g., new templating syntax) are supported.
################################################################################
engine: ">=3.9.0"