apiVersion: v2
name: taskstream-web
description: "Production-grade Helm Chart for TaskStream AI Web Frontend Application with high availability, monitoring, and security features"
type: application
version: "1.0.0"
appVersion: "1.0.0"

keywords:
  - "taskstream"
  - "web"
  - "frontend"
  - "react"
  - "high-availability"
  - "monitored"
  - "enterprise"

home: "https://taskstream.ai"
sources:
  - "https://github.com/taskstream/taskstream-ai"

maintainers:
  - name: "TaskStream DevOps Team"
    email: "devops@taskstream.ai"
    url: "https://taskstream.ai/team"

annotations:
  artifacthub.io/changes: "Initial production release of TaskStream AI Web Frontend with high availability and monitoring"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/recommendations: "true"
  artifacthub.io/signKey: "verified"
  prometheus.io/scrape: "true"
  prometheus.io/port: "9090"

dependencies:
  - name: ingress-nginx
    version: "4.7.1"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: "ingress.enabled"
    tags:
      - "ingress"
      - "loadbalancer"
  - name: prometheus
    version: "25.3.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: "monitoring.enabled"
    tags:
      - "monitoring"
      - "metrics"